Adding exam edit endpoint
FrosTiK-SD/tpc-exam-backend pull request #22
Opened 2023-08-15 10:23 UTC by SakshiSharan

Added exam edit put endpoint (/exam/id/edit). Edit logic does not change the seat and venue of the student if their venue is still present in the new edited exam. For already completed exams, retains attendance information (Not recommended to edit in already completed exams as it may lead to loss of attendance data).

2023-08-15 11:05 UTC, Shubhrajyoti-Dey-FrosTiK requested changes

2023-08-15 11:05 UTC, Shubhrajyoti-Dey-FrosTiK commented on controller/exam.go
> +	cursor, err = client.Database(constants.DB).Collection(constants.COLLECTION_ATTENDANCE).Aggregate(ctx,
What we should do here is

We have the new roll nos

So have a `find` query in the `STUDENT` collection to get the `objectID`s 

Now in the `oldAttendances` just do a `find` query with `examID`

Now match the `_id` and edit the algo for venue allocatin by replacing the `rollNo` with `objectID`s.

You can convert `objectID` to string using `objectIDVar.Hex()`

2023-08-15 11:05 UTC, Shubhrajyoti-Dey-FrosTiK commented on utils/distributer.go
> +			if(newStudent == oldStudent.UserDetails[0].RollNo) {
Just replace by `_id`

2023-08-16 05:53 UTC, SakshiSharan commented on controller/exam.go
> +func EditExamById(ctx *gin.Context, client *mongo.Client, createExamRequest *request.CreateExam, id *primitive.ObjectID) (*model.Examination, *[]interface{}, error) {
This is not a predetermined struct as we need []interface{} to perform InsertMany query to insert attendances in Mongo. Mongo cannot marshal slice of structs into slice of interface by itself, however it can do so for a single struct.
But we can use predetermined structs and before inserting into Mongo we can explicitly create a slice of interfaces by appending each struct item from the slice of structs into the slice of interfaces. This works.

2023-08-16 06:34 UTC, Shubhrajyoti-Dey-FrosTiK commented on controller/exam.go
> +func EditExamById(ctx *gin.Context, client *mongo.Client, createExamRequest *request.CreateExam, id *primitive.ObjectID) (*model.Examination, *[]interface{}, error) {
Ok keep it as it is.

But is there any way we can return a pre-determined struct from the `controller` at least. No problem to return a interface from `mapper` but it would be better if we could return a predetermined struct from `controller` for code readability standpoint

2023-08-16 11:29 UTC, SakshiSharan commented on controller/exam.go
> +func EditExamById(ctx *gin.Context, client *mongo.Client, createExamRequest *request.CreateExam, id *primitive.ObjectID) (*model.Examination, *[]interface{}, error) {
Yes, definitely. Further code change will reflect this.

2023-08-17 12:15 UTC, SakshiSharan commented on controller/exam.go
> +	cursor, err = client.Database(constants.DB).Collection(constants.COLLECTION_ATTENDANCE).Aggregate(ctx,
resolved by using primitive.ObjectID as keys instead of using rollnos.

2023-08-17 12:15 UTC, SakshiSharan commented on utils/distributer.go
> +			if(newStudent == oldStudent.UserDetails[0].RollNo) {
done.

2023-08-18 06:04 UTC, Shubhrajyoti-Dey-FrosTiK commented on controller/exam.go
> +func CreateExam(ctx *gin.Context, client *mongo.Client, createExamRequest *request.CreateExam) (*model.Examination, *[]model.Attendance, error) {
Nice

2023-08-18 06:07 UTC, Shubhrajyoti-Dey-FrosTiK approved these changes

2023-08-18 06:07 UTC, merged